'------------------------------------------------------------------------------
' <auto-generated>
'    Dieser Code wurde aus einer Vorlage generiert.
'
'    Manuelle Änderungen an dieser Datei führen möglicherweise zu unerwartetem Verhalten Ihrer Anwendung.
'    Manuelle Änderungen an dieser Datei werden überschrieben, wenn der Code neu generiert wird.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class BrancheEntity
    Public Property BrIdPk As Integer
    Public Property BrTitel As String
    Public Property BrVersion As Byte()

    Public Overridable Property tblInfluencer As ICollection(Of InfluencerEntity) = New HashSet(Of InfluencerEntity)
    Public Overridable Property tblJobanzeigen As ICollection(Of JobanzeigeEntity) = New HashSet(Of JobanzeigeEntity)
    Public Overridable Property tblUnternehmer As ICollection(Of UnternehmerEntity) = New HashSet(Of UnternehmerEntity)

End Class
