'------------------------------------------------------------------------------
' <auto-generated>
'    Dieser Code wurde aus einer Vorlage generiert.
'
'    Manuelle Änderungen an dieser Datei führen möglicherweise zu unerwartetem Verhalten Ihrer Anwendung.
'    Manuelle Änderungen an dieser Datei werden überschrieben, wenn der Code neu generiert wird.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Data.Entity
Imports System.Data.Entity.Infrastructure
Imports collab_asp

Partial Public Class collabEntities
    Inherits DbContext

    Public Sub New()
        MyBase.New("name=collabEntities")
    End Sub

    Protected Overrides Sub OnModelCreating(modelBuilder As DbModelBuilder)
        Throw New UnintentionalCodeFirstException()
    End Sub

    Public Property tblBranchen() As DbSet(Of BrancheEntity)
    Public Property tblInfluencer() As DbSet(Of InfluencerEntity)
    Public Property tblJobanzeigen() As DbSet(Of JobanzeigeEntity)
    Public Property tblUnternehmer() As DbSet(Of UnternehmerEntity)

    Friend Function Entry(jobEntity As JobanzeigeEntity) As Object
        Throw New NotImplementedException()
    End Function

    Friend Sub SaveChanges()
        Throw New NotImplementedException()
    End Sub
End Class
