'------------------------------------------------------------------------------
' <auto-generated>
'    Dieser Code wurde aus einer Vorlage generiert.
'
'    Manuelle Änderungen an dieser Datei führen möglicherweise zu unerwartetem Verhalten Ihrer Anwendung.
'    Manuelle Änderungen an dieser Datei werden überschrieben, wenn der Code neu generiert wird.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class JobanzeigeEntity
    Public Property JaIdPk As Integer
    Public Property JaTitel As String
    Public Property JaBeschreibung As String
    Public Property JaUIdFk As Nullable(Of Integer)
    Public Property JaInIdFk As Nullable(Of Integer)
    Public Property JaBrIdFk As Nullable(Of Integer)

    Public Overridable Property tblBranchen As BrancheEntity
    Public Overridable Property tblInfluencer As InfluencerEntity
    Public Overridable Property tblUnternehmer As UnternehmerEntity

End Class
