'------------------------------------------------------------------------------
' <auto-generated>
'    Dieser Code wurde aus einer Vorlage generiert.
'
'    Manuelle Änderungen an dieser Datei führen möglicherweise zu unerwartetem Verhalten Ihrer Anwendung.
'    Manuelle Änderungen an dieser Datei werden überschrieben, wenn der Code neu generiert wird.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class UnternehmerEntity
    Public Property UIdPk As Integer
    Public Property UName As String
    Public Property UBrIdFk As Nullable(Of Integer)
    Public Property UBenutzername As String
    Public Property UPasswort As String
    Public Property UEMail As String
    Public Property UVersion As Byte()

    Public Overridable Property tblBranchen As BrancheEntity
    Public Overridable Property tblJobanzeigen As ICollection(Of JobanzeigeEntity) = New HashSet(Of JobanzeigeEntity)

End Class
